dotenv: .env

networks:
  sepolia:
    host: https://sepolia.infura.io/v3/${WEB3_INFURA_PROJECT_ID}
    chainid: 11155111
    explorer: https://api-sepolia.etherscan.io/api
    verify: True

wallets:
  from_key: ${PRIVATE_KEY_METAMASK}
